### PR TITLE
Fix sed not working

### PR DESCRIPTION
**Pull request by Suika**
sed \\ will not work, \\\ will. You need to escape the escape character, to escape the escape character. Not \\, nor \\\\, but \\\.

### CODE REVIEW

**Comment by crazy-max** [comment]
Please split your PR. One to fix sed and another for WEBUI_PORT. Thanks.

**Comment by Suika** [comment]
Just accept this one, I'll push another one later because at this point I can't be bothered anymore. Frankly it took me far more time to try to figure out this PR splitting bullshit with commits that stack on each other than to find the problem, firgure it out and build/test it multiple times. And I still don't know how to split them to be each own PRs for each commit wihout another branch having... just killme.

**Comment by Suika** [comment]
Or just patch it directly since I don't care about attribution.

**Review by crazy-max — APPROVED** [review]
LGTM thanks

**Pull request merged**
